baseURL = "https://shigekikarita.github.io/log/"
languageCode = "jp"
paginate = "10" # Number of posts per page
hasCJKLanguage = true
title = "log"
theme = "mainroad"
googleAnalytics = "UA-139201189-1"

pygmentsCodefences=true

[Author] # Used in authorbox
  name = "Shigeki Karita"
  bio = "D language man."
  avatar = "img/avatar.jpg"


[Params]
  subtitle = "of karita" # Subtitle of your site. Used in site header
  description = "personal blog about everything" # Site description. Used in meta description
  copyright = "karitech" # copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information. Use ["none"] to turn off completely.
  postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
  #postSections = ["blog", "news"] # alternative that shows more than one section's pages
  dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  customCSS = ["css/custom.css"] # Include custom CSS files


[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "kari_tech"
  github = "ShigekiKarita"
  email = "shigekikarita@gmail.com"
