baseURL = "https://shigekikarita.github.io/log/"
languageCode = "jp"
paginate = "10" # Number of posts per page
hasCJKLanguage = true
title = "log"
theme = "mainroad"
googleAnalytics = "UA-139201189-1"

pygmentsCodefences=true

[Author] # Used in authorbox
  name = "Shigeki Karita"
  bio = "D言語と日々の研究について雑記"
  avatar = "img/avatar.jpg"

[menu]

  [[menu.main]]
    identifier = "root"
    name = "home"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://shigekikarita.github.io"
    weight = -110
  [[menu.main]]
    identifier = "github"
    name = "github"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://github.com/ShigekiKarita/log"
    weight = -10

[Params]
  subtitle = "" # Subtitle of your site. Used in site header
  description = "personal blog about everything" # Site description. Used in meta description
  copyright = "karita" # copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information. Use ["none"] to turn off completely.
  postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
  #postSections = ["blog", "news"] # alternative that shows more than one section's pages
  dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  customCSS = ["css/custom.css"] # Include custom CSS files


[Params.sidebar]
  home = "left" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "kari_tech"
  github = "ShigekiKarita"
  email = "karita@ieee.org"
