#+title: スマホでコーディング
#+summary:
#+categories: Programming
#+tags: Android D
#+draft: true
#+date: 2019-06-24T23:14:33+09:00
#+author: Shigeki Karita
#+isCJKLanguage: true
#+markup: org
#+toc: false

** tl;dr

正気を失ったかと思われるかもしれませんが、Andridスマホを屋外での開発機にしようと思いました。夏になるとノートPCを背負って移動が嫌なので。。。

** TODO ハードウェア

+ LG Nexus 5X
+ iClever IC-03BK
+ ELECOM CAPCLIP

マウスとキーボードは新しいやつ購入。とにかく小さいやつが欲しかったのです。打ち心地とか悪くないけど、US配列は未だに慣れません。Caps/CTRL入替は親指CTRLというアプリでできました。


** TODO リモートの開発環境

さすがにスマホは一時的な環境として、同期も面倒だしGPUは積んでないので、自宅マシンに接続して開発することにしました。そのためのルータのポート開放とかDDNS設定した(この辺は素人知識でやるとセキュリティ的に不味そうなので手順は省略)。

スマホからのSSH接続はJuiceSSHというアプリを Google Play で入れました。


** TODO ローカルの開発環境

リモートに接続不要な作業はローカルでやろうと思い、Termux というアプリを Google Play で入れました。とりあえずD言語が書ければいいので、こんな感じでpkgいれました。

#+begin_src bash
$ pkg install ldc git emacs
$ termux-setup-storage
#+end_src

二行目はストレージのアクセス権を取得します。 ~$HOME/storage~ 以下に download などのフォルダがでてきますが、root化していないのでOS用の領域など全て見れるわけではないです。

** Emacs 便利なショートカット

とりあえず、Emacsで全てをやっているのですが、やはりどんな環境でも動くのがすごい。SSHもtramp使えばよかったか。

全体。US配列はじめての人。

+ ~C-/~ これundoだったんですね。 ~C-_~ 派でしたがUSだとうちにくい。
+ ~M-x~ メタキー全般なんですが、光りのはやさで入力しないと絵文字パレットがでてくる

IME関連。とりあえず日本語入力はEmacsに頼る。

+ ~C-\~ EmacsのIMEを起動
+ IMEモードで ~qq~ ローマ字入力切替
+ IMEモードで ~K~ カタカナ変換

http://www.ice.gunma-ct.ac.jp/~mame/kougi/kisoron/japanese.html
